### ISSUE TITLE
Connect to Ably Realtime using socket_io_client

### ISSUE THREAD

**Issue by Nealsoni00** [ably/ably-flutter#148]
Hey! I want to connect to ably on Flutter Desktop (MacOS/Windows) so I am unable to use the `ably-flutter` package.

Is it possible to connect to ably real-time using the [socket.io client](https://pub.dev/packages/socket_io_client) for flutter? Instructions on how to do this would be a good stopgap for the short-term solving a portion of #76.

Thanks!

**Comment by ben-xD** [comment]
Hey @Nealsoni00, unfortunately socket.io does not support connecting to Ably, this feature would need to be added to their library. So this would be a request for socket.io more than for Ably, since we do provide the details on how to connect to Ably. However, the adding support for Ably in socket.io would be complicated/ quite involved, as we have [different features](https://ably.com/documentation/how-ably-works). For example, Ably provides presence, integration with other Ably features (reactor, push notifications), whereas Socket.io falls back to `http`. We have found that sticking to WebSockets for realtime channel messages works well, as Web Sockets are supported on [98.17%](https://caniuse.com/websockets) machines globally.

**Comment by ben-xD** [comment]
@Nealsoni00, you could actually connect to Ably using MQTT though, since Ably supports a MQTT Adapter, which translates back and forth between MQTT and Ably's protocol. This means [mqtt_client](https://pub.dev/packages/mqtt_client) _should_ work.

Take a look at https://ably.com/documentation/mqtt and https://pub.dev/packages/mqtt_client

**Comment by richard457** [comment]
@ben-xD can you share a working example? I appreciate

**Comment by richard457** [comment]
tried final client = MqttServerClient('mqtt.ably.io',
    'crarPQ.t0xNhA:z0F8ZSFXk-MsNEtwVYVdfcx6KmPFNuGhd1R');
where ```crarPQ.t0xNhA:z0F8ZSFXk-MsNEtwVYVdfcx6KmPFNuGhd1R81nD``` is ably Private API Key
and connect like this: ``` /// Set logging on if needed, defaults to off
    client.logging(on: false);

    /// If you intend to use a keep alive you must set it here otherwise keep alive will be disabled.
    client.keepAlivePeriod = 20;

    /// Add the unsolicited disconnection callback
    client.onDisconnected = onDisconnected;

    /// Add the successful connection callback
    client.onConnected = onConnected;

    /// Add a subscribed callback, there is also an unsubscribed callback if you need it.
    /// You can add these before connection or change them dynamically after connection if
    /// you wish. There is also an onSubscribeFail callback for failed subscriptions, these
    /// can fail either because you have tried to subscribe to an invalid topic or the broker
    /// rejects the subscribe request.
    client.onSubscribed = onSubscribed;

    /// Set a ping received callback if needed, called whenever a ping response(pong) is received
    /// from the broker.
    client.pongCallback = pong;

    /// Create a connection message to use or use the default one. The default one sets the
    /// client identifier, any supplied username/password and clean session,
    /// an example of a specific one below.
    final connMess = MqttConnectMessage()
        .withClientIdentifier(
            'crarPQ.t0xNhA:z0F8ZSFXk-MsNEtwVYVdfcx6KmPFNuGhd1R81nDWlc0')
        .startClean() // Non persistent session for testing
        .withWillQos(MqttQos.atLeastOnce);
    log.d('EXAMPLE::Mosquitto client connecting....');
    client.connectionMessage = connMess;

    /// Connect the client, any errors here are communicated by raising of the appropriate exception. Note
    /// in some circumstances the broker will just disconnect us, see the spec about this, we however will
    /// never send malformed messages.
    try {
      await client.connect();
    } on NoConnectionException catch (e) {
      // Raised by the client when connection fails.
      log.d('EXAMPLE::client exception - $e');
      client.disconnect();
    } on SocketException catch (e) {
      // Raised by the socket layer
      log.d('EXAMPLE::socket exception - $e');
      client.disconnect();
    }```

**Comment by richard457** [comment]
but the above code seems to not connect, any tip?
