### ISSUE TITLE
Building Example App on Android fails

### ISSUE THREAD

**Issue by davyskiba** [ably/ably-flutter#418]
Building Example App on Android fails with the following error:
> Launching lib/main.dart on Android SDK built for x86 64 in debug mode...
> lib/main.dart:1
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:processDebugGoogleServices'.
> > Missing Google App Id. Please follow instructions on https://firebase.google.com/ to get a valid config file that contains a Google App Id
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 12s
> Exception: Gradle task assembleDebug failed with exit code 1
> Exited

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1933) by [Unito](https://www.unito.io)

**Comment by ikurek** [comment]
The issue seems to be the [google-services.json](https://github.com/ably/ably-flutter/blob/main/example/android/app/src/google-services.json) file - back in https://github.com/ably/ably-flutter/pull/344 I added an empty `google-services.json` file to allow users to run the app without any configuration (before users had to generate the file and manually add it to the example app). I guess we have to put some values into this file, we already have a test instance of Firebase, so we may use that.

Also, as @QuintinWillison and @ikbalkaya suggested, we can avoid issues like that by extending our CI to verify the example app: https://github.com/ably/ably-flutter/issues/419
