### ISSUE TITLE
int value is changed to double on Android

### ISSUE THREAD

**Issue by Afur** [ably/ably-flutter#461]
Hey, on Android I'm facing an issue where all of my `int` values from json passed in message as `data` are converted to `double` on Dart side. 

Example: 

I send as `data`:
```
object: {
   year: 2021,
} 
```

I receive as `Message.data` (only on Android, iOS works fine): 
```
object: {
   year: 2021.0,
} 
```

**Comment by owenpearson** [comment]
Hey @Afur, thank you for raising this! We will investigate and see if there's something we can do to prevent this behaviour. The underlying cause of this problem is that the android version of ably-flutter uses Gson internally and this is just [the default behaviour of Gson](https://stackoverflow.com/questions/15507997/how-to-prevent-gson-from-expressing-integers-as-floats).

As a workaround it should be possible to publish the messages as json encoded strings and decode them in your own application code, or just simply cast the values to `int`s upon receipt of the message. Please let us know if you need any further help.

**Comment by Afur** [comment]
Thanks for the fast response, [this](https://stackoverflow.com/a/70229243) solution looks promising. I'll check locally if the library upgrade and that as a fix works for now. Eventually, I'll submit PR with that and you'll test whether it covers all yours use cases or didn't break something.

**Comment by Afur** [comment]
Issue still exists I've added comment in #462. Code with fix is missing on main even when PR is merged. Probably has been removed with some merge conflicts commit

**Comment by owenpearson** [comment]
Hey @Afur, thanks for raising this. 

You're right that the changes in your commit were mistakenly removed during a merge, I've opened #486 to apply the changes again. Really sorry for the inconvenience here.
