### ISSUE TITLE
Defaults: Generate environment fallbacks

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-flutter#47]
### Generic Specification

Per `RSC15g`, introduced in https://github.com/ably/docs/pull/965.

See https://github.com/ably/ably-js/pull/682 and https://github.com/ably/ably-ruby/pull/196 for reference implementations.

### Flutter Specific Notes

Given this client library is a plugin (i.e. delegates most of its work to native implementations), I'm not sure how much work is required to to make this happen as the majority (if not all) of the work to complete this may be required to be completed in the upstream native dependencies via:

- https://github.com/ably/ably-cocoa/issues/1066
- https://github.com/ably/ably-java/issues/603

**Comment by tiholic** [comment]
@QuintinWillison Yes, only change to be handled is to deprecate `fallbackHostsUseDefault`

**Comment by QuintinWillison** [comment]
We need to look at whether any work is required before we can safely close this issue.

**Comment by ikurek** [comment]
@QuintinWillison I think it was done as a side-effect of #69 in commit https://github.com/ably/ably-flutter/commit/4d21e7cb1b9fb43b89792a4288ec2609bf45b827, the `@deprecated` annotation was added on `fallbackHostsUseDefault` field. I don't think there's anything more we have to do with this, since the rest seems to be handled by java and cocoa libs, so I'm closing this for now
