### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by tiholic** [ably/ably-flutter#82]
Refer to the migration guide: https://dart.dev/null-safety/migration-guide

_Note: null safety is supported in dart SDK > 2.12_

**Comment by heshanka** [comment]
Is there any progress about this issue?

**Comment by QuintinWillison** [comment]
Hello @heshanka - we definitely feel that migration to null safety will bring benefits to developers using this plugin so this issue is definitely towards the top of our backlog, however we can't currently promise when it'll be delivered as there are still a few fundamental features which we're working on ahead of this.
